version: '3.8'
services:
    dev-db:
        image: postgres:15.1
        ports:
            - 5434:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: pef-development
        networks:
            - pef
    test-db:
        image: postgres:15.1
        ports:
            - 5435:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: pef-test
        networks:
            - pef
    prod-db:
        image: postgres:15.1
        ports:
            - 5436:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123
            POSTGRES_DB: pef-production
        networks:
            - pef
networks:
    pef:
